### PR TITLE
Fixes #15 Remove new line from json parser

### LINKED ISSUE #15: New line issue in the "json" helper
# Issue description
The 'json' helper function adds an extra new line at the end of the parsed object. This happens because the parsed result is inside the `<pre>` HTML tag.
## Example
```
{
    "title": "This is an example object",
    "message": "The 'json' helper will add an additional new line after the object"
}
                     
```

# Proposed solution
Remove the new line from the parsed 'json' objects:
in the file `/handlebars/helpers.js` modify the line 171 in order to make it like:
```
return new Handlebars.SafeString($.html().replace(/\n/g, ''))
```

_If you want I can submit a Pull Request._

### PR DESCRIPTION
**Pull request by marc0l92**

### CODE REVIEW

**Comment by nknapp** [comment]
I'll have to check why the tests are failing. But it has failed before already. Looks like something else is broken

**Comment by nknapp** [comment]
Oh, could you add a test here: ,https://github.com/bootprint/bootprint-base/blob/d7cf28bda8dfa5ae95a2c67c2147b3fd43ec85f6/test/helper-spec.js#L100

**Comment by nknapp** [comment]
I'd like to rebase your branch on the current master to see what the tests are doing with your commit. Is that OK?

**Comment by marc0l92** [comment]
Yes, It is ok.
I'm not an expert of GIT in general therefore if you think that a rebase can solve the testing issues do it.

I will look at the test that you request me in the weekend.

**Comment by marc0l92** [comment]
I'm trying to run the testing scripts (`npm test`) but I get this errror:

```
warning: you are using async-hook which is unstable.
....\bootprint-base\node_modules\stack-chain\index.js:10
    throw new Error('Conflicting version of stack-chain found');
    ^

Error: Conflicting version of stack-chain found
```

Do you know how to solve it? It seems that there is a problem with a dependency.

**Pull request closed without merging**
